### ISSUE TITLE
Nested dependencies

### ISSUE THREAD

**Issue by RWOverdijk** [h2non/requireg#11]
Hey, cool module. Quick question...

When NPM discovers a versioning conflict, it'll install dependencies nested elsewhere in the directory tree. Have you solved this? If so, how? Right now I can only require modules from a global path if there are no conflicts and they get installed in node_modules

**Comment by h2non** [comment]
That's not currently supported and would make things too complex for the scope of this package. Basically, it's required to walk the dependency tree and visit each package.json in order to discover conflicts, pretty much as npm/yarn does.

**Comment by RWOverdijk** [comment]
Yeah I thought as much... It makes a global discovery tool difficult to build. I tried just traversing targets but it's undoable.

All right, thanks!
