### ISSUE TITLE
Can't require "npm install -g" installed packages on windows

### ISSUE THREAD

**Issue by Laguana** [h2non/requireg#4]
I tried out requireg today, but I saw that it doesn't seem to check %appdata%\npm\node_modules on windows, which seems to be where modules are globally installed to by default.

**Comment by h2non** [comment]
There're a bit of inconsistency in Windows npm native place. 
`requireg`, as final strategy, will try to resolve modules looking up via NODE_PATH environment variable. It's recommended to define it (specially in Windows).

You can read more here:
https://nodejs.org/docs/latest/api/modules.html#modules_loading_from_the_global_folders

**Comment by gbaumgart** [comment]
same here, please add these paths to requireg, otherwise it makes little sense after all.

**Comment by gbaumgart** [comment]
it needs only: process.env.APPDATA + '/npm/' to be added to make it working on windows

**Comment by h2non** [comment]
Please, go ahead with a PR and I'll release a fresh version with that feature.

**Comment by gbaumgart** [comment]
Please grab it from here: https://github.com/gbaumgart/requireg/blob/master/lib/resolvers.js. Not sure about the order but it works great for me.

**Comment by xblox** [comment]
hi, for some reason requireg prefers a local module over the global. is that intended ?

**Comment by h2non** [comment]
Yes, that the default behaviour, however, it can be easily reverted, but that's not supported yet.

**Comment by xblox** [comment]
hi, ok. never mind. this is confusing because its supposed to be loading global modules, I would understand the fallback to local if global isn't there, but ok.

**Comment by h2non** [comment]
The current implementation tends to be more `node.js` module lookup behaviour friendly first. 
I can agree that under certain scenarios you might require a different behaviour. I had not that need so that's why I didn't implement that. 
It should be trivial to modify the current behaviour anyway. I always accept PRs.
